[package]
name = "nx-service-friends"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_service_friends"
crate-type = ["rlib"]
test = false
doctest = false
bench = false

[dependencies]
nx-panic-handler = { version = "0.1.0", path = "../nx-panic-handler" }
nx-service-sm = { version = "0.1.0", path = "../nx-service-sm" }
nx-sf = { version = "0.1.0", path = "../nx-sf" }
nx-sys-thread-tls = { version = "0.1.0", path = "../nx-sys-thread-tls" }
nx-std-sync = { version = "0.1.0", path = "../nx-std-sync" }
static_assertions = "1"
thiserror = { version = "2", default-features = false }
