[workspace]
resolver = "2"
members = [
    "subprojects/nx-alloc",
    "subprojects/nx-cpu",
    "subprojects/nx-display",
    "subprojects/nx-net",
    "subprojects/nx-netloader",
    "subprojects/nx-nv",
    "subprojects/nx-fsdev",
    "subprojects/nx-panic-handler",
    "subprojects/nx-pm",
    "subprojects/nx-rand",
    "subprojects/nx-rt-core",
    "subprojects/nx-rt-kip",
    "subprojects/nx-rt-module",
    "subprojects/nx-rt-nro",
    "subprojects/nx-rt-nso",
    "subprojects/nx-service-acc",
    "subprojects/nx-service-apm",
    "subprojects/nx-service-async",
    "subprojects/nx-service-applet",
    "subprojects/nx-service-applet-album",
    "subprojects/nx-service-applet-err",
    "subprojects/nx-service-applet-friends",
    "subprojects/nx-service-applet-hid",
    "subprojects/nx-service-applet-mii",
    "subprojects/nx-service-applet-nfp",
    "subprojects/nx-service-applet-pctlauth",
    "subprojects/nx-service-applet-psel",
    "subprojects/nx-service-aud",
    "subprojects/nx-service-audctl",
    "subprojects/nx-service-auddev",
    "subprojects/nx-service-audin",
    "subprojects/nx-service-audout",
    "subprojects/nx-service-audrec",
    "subprojects/nx-service-audren",
    "subprojects/nx-service-avm",
    "subprojects/nx-service-bpc",
    "subprojects/nx-service-bsd",
    "subprojects/nx-service-bt",
    "subprojects/nx-service-btdrv",
    "subprojects/nx-service-btm",
    "subprojects/nx-service-btmsys",
    "subprojects/nx-service-btmu",
    "subprojects/nx-service-capmtp",
    "subprojects/nx-service-caps",
    "subprojects/nx-service-capsa",
    "subprojects/nx-service-capsc",
    "subprojects/nx-service-capsdc",
    "subprojects/nx-service-capssc",
    "subprojects/nx-service-capssu",
    "subprojects/nx-service-capsu",
    "subprojects/nx-service-clkrst",
    "subprojects/nx-service-csrng",
    "subprojects/nx-service-ectx",
    "subprojects/nx-service-fan",
    "subprojects/nx-service-fatal",
    "subprojects/nx-service-fs",
    "subprojects/nx-service-friends",
    "subprojects/nx-service-fsldr",
    "subprojects/nx-service-fspr",
    "subprojects/nx-service-gpio",
    "subprojects/nx-service-grc",
    "subprojects/nx-service-hid",
    "subprojects/nx-service-hidbus",
    "subprojects/nx-service-hiddbg",
    "subprojects/nx-service-hidsys",
    "subprojects/nx-service-htcs",
    "subprojects/nx-service-hwopus",
    "subprojects/nx-service-i2c",
    "subprojects/nx-service-idlesys",
    "subprojects/nx-service-ins",
    "subprojects/nx-service-irs",
    "subprojects/nx-service-lbl",
    "subprojects/nx-service-ldn",
    "subprojects/nx-service-ldr",
    "subprojects/nx-service-lp2p",
    "subprojects/nx-service-lr",
    "subprojects/nx-service-mii",
    "subprojects/nx-service-miiimg",
    "subprojects/nx-service-mm",
    "subprojects/nx-service-ncm",
    "subprojects/nx-service-nfc",
    "subprojects/nx-service-news",
    "subprojects/nx-service-nifm",
    "subprojects/nx-service-nim",
    "subprojects/nx-service-notif",
    "subprojects/nx-service-ns",
    "subprojects/nx-service-omm",
    "subprojects/nx-service-ovln",
    "subprojects/nx-service-nv",
    "subprojects/nx-service-pctl",
    "subprojects/nx-service-pcv",
    "subprojects/nx-service-pdm",
    "subprojects/nx-service-pgl",
    "subprojects/nx-service-pl",
    "subprojects/nx-service-pm",
    "subprojects/nx-service-psm",
    "subprojects/nx-service-psc",
    "subprojects/nx-service-ro",
    "subprojects/nx-service-set",
    "subprojects/nx-service-sfdnsres",
    "subprojects/nx-service-sm",
    "subprojects/nx-service-smm",
    "subprojects/nx-service-spl",
    "subprojects/nx-service-spsm",
    "subprojects/nx-service-ssl",
    "subprojects/nx-service-tc",
    "subprojects/nx-service-time",
    "subprojects/nx-service-ts",
    "subprojects/nx-service-uart",
    "subprojects/nx-service-usbds",
    "subprojects/nx-service-usbhs",
    "subprojects/nx-service-vi",
    "subprojects/nx-service-wlaninf",
    "subprojects/nx-sf",
    "subprojects/nx-std",
    "subprojects/nx-std-fs",
    "subprojects/nx-std-path",
    "subprojects/nx-std-sync",
    "subprojects/nx-svc",
    "subprojects/nx-sys-args",
    "subprojects/nx-sys-fd",
    "subprojects/nx-sys-mem",
    "subprojects/nx-sys-net",
    "subprojects/nx-sys-sync",
    "subprojects/nx-sys-thread",
    "subprojects/nx-sys-thread-tls",
    "subprojects/nx-sys-virtmem",
    "subprojects/nx-time",
    "subprojects/nx-wlaninf",
]

[workspace.dependencies]
zerocopy = { version = "0.8", default-features = false, features = ["derive"] }
