[package]
name = "nx-sys-mem"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_sys_mem"
crate-type = ["rlib"]
test = false
doctest = false
bench = false

[features]
# Enable the __nx_sys_mem FFI
ffi = []

[dependencies]
nx-alloc = { version = "0.1.0", path = "../nx-alloc", features = ["global-allocator"] }
nx-panic-handler = { version = "0.1.0", path = "../nx-panic-handler" }
nx-svc = { version = "0.1.0", path = "../nx-svc" }
nx-sys-virtmem = { version = "0.1.0", path = "../nx-sys-virtmem" }
thiserror = { version = "2.0.12", default-features = false }
