use nx_sf::ServiceName;

pub const SERVICE_NAME: ServiceName = ServiceName::new_truncate("fsp-srv");

pub const FS_POOL_SIZE: usize = 3;

// IFileSystemProxy
pub const PROXY_OPEN_FILE_SYSTEM: u32 = 0;
pub const PROXY_SET_CURRENT_PROCESS: u32 = 1;
pub const PROXY_OPEN_DATA_FILE_SYSTEM_BY_CURRENT_PROCESS: u32 = 2;
pub const PROXY_OPEN_FILE_SYSTEM_WITH_PATCH: u32 = 7;
pub const PROXY_OPEN_FILE_SYSTEM_WITH_ID: u32 = 8;
pub const PROXY_OPEN_DATA_FILE_SYSTEM_BY_PROGRAM_ID: u32 = 9;
pub const PROXY_OPEN_FILE_SYSTEM_WITH_ID_V16: u32 = 10;
pub const PROXY_OPEN_BIS_FILE_SYSTEM: u32 = 11;
pub const PROXY_OPEN_BIS_STORAGE: u32 = 12;
pub const PROXY_OPEN_HOST_FILE_SYSTEM: u32 = 17;
pub const PROXY_OPEN_SD_CARD_FILE_SYSTEM: u32 = 18;
pub const PROXY_DELETE_SAVE_DATA_FILE_SYSTEM: u32 = 21;
pub const PROXY_CREATE_SAVE_DATA_FILE_SYSTEM: u32 = 22;
pub const PROXY_CREATE_SAVE_DATA_FILE_SYSTEM_BY_SYSTEM_SAVE_DATA_ID: u32 = 23;
pub const PROXY_DELETE_SAVE_DATA_FILE_SYSTEM_BY_SAVE_DATA_SPACE_ID: u32 = 25;
pub const PROXY_IS_EXFAT_SUPPORTED: u32 = 27;
pub const PROXY_DELETE_SAVE_DATA_FILE_SYSTEM_BY_SAVE_DATA_ATTRIBUTE: u32 = 28;
pub const PROXY_OPEN_GAME_CARD_FILE_SYSTEM: u32 = 31;
pub const PROXY_EXTEND_SAVE_DATA_FILE_SYSTEM: u32 = 32;
pub const PROXY_OPEN_HOST_FILE_SYSTEM_WITH_OPTION: u32 = 36;
pub const PROXY_OPEN_SAVE_DATA_FILE_SYSTEM: u32 = 51;
pub const PROXY_OPEN_SAVE_DATA_FILE_SYSTEM_BY_SYSTEM_SAVE_DATA_ID: u32 = 52;
pub const PROXY_OPEN_READ_ONLY_SAVE_DATA_FILE_SYSTEM: u32 = 53;
pub const PROXY_READ_SAVE_DATA_FILE_SYSTEM_EXTRA_DATA_BY_SAVE_DATA_SPACE_ID: u32 = 57;
pub const PROXY_READ_SAVE_DATA_FILE_SYSTEM_EXTRA_DATA: u32 = 58;
pub const PROXY_WRITE_SAVE_DATA_FILE_SYSTEM_EXTRA_DATA: u32 = 59;
pub const PROXY_OPEN_SAVE_DATA_INFO_READER: u32 = 60;
pub const PROXY_OPEN_SAVE_DATA_INFO_READER_BY_SAVE_DATA_SPACE_ID: u32 = 61;
pub const PROXY_OPEN_SAVE_DATA_INFO_READER_WITH_FILTER: u32 = 68;
pub const PROXY_OPEN_IMAGE_DIRECTORY_FILE_SYSTEM: u32 = 100;
pub const PROXY_OPEN_CONTENT_STORAGE_FILE_SYSTEM: u32 = 110;
pub const PROXY_OPEN_CUSTOM_STORAGE_FILE_SYSTEM: u32 = 130;
pub const PROXY_OPEN_DATA_STORAGE_BY_CURRENT_PROCESS: u32 = 200;
pub const PROXY_OPEN_DATA_STORAGE_BY_PROGRAM_ID: u32 = 201;
pub const PROXY_OPEN_DATA_STORAGE_BY_DATA_ID: u32 = 202;
pub const PROXY_OPEN_PATCH_DATA_STORAGE_BY_CURRENT_PROCESS: u32 = 203;
pub const PROXY_OPEN_DEVICE_OPERATOR: u32 = 400;
pub const PROXY_OPEN_SD_CARD_DETECTION_EVENT_NOTIFIER: u32 = 500;
pub const PROXY_GET_RIGHTS_ID_BY_PATH: u32 = 609;
pub const PROXY_GET_RIGHTS_ID_AND_KEY_GENERATION_BY_PATH: u32 = 610;
pub const PROXY_GET_PROGRAM_ID: u32 = 618;
pub const PROXY_IS_SIGNED_SYSTEM_PARTITION_ON_SD_CARD_VALID: u32 = 640;
pub const PROXY_GET_AND_CLEAR_ERROR_INFO: u32 = 800;
pub const PROXY_GET_CONTENT_STORAGE_INFO_INDEX: u32 = 820;
pub const PROXY_DISABLE_AUTO_SAVE_DATA_CREATION: u32 = 1003;
pub const PROXY_SET_GLOBAL_ACCESS_LOG_MODE: u32 = 1004;
pub const PROXY_GET_GLOBAL_ACCESS_LOG_MODE: u32 = 1005;
pub const PROXY_OUTPUT_ACCESS_LOG_TO_SD_CARD: u32 = 1006;
pub const PROXY_GET_PROGRAM_INDEX_FOR_ACCESS_LOG: u32 = 1007;
pub const PROXY_GET_AND_CLEAR_MEMORY_REPORT_INFO: u32 = 1009;

// IFileSystem
pub const FS_CREATE_FILE: u32 = 0;
pub const FS_DELETE_FILE: u32 = 1;
pub const FS_CREATE_DIRECTORY: u32 = 2;
pub const FS_DELETE_DIRECTORY: u32 = 3;
pub const FS_DELETE_DIRECTORY_RECURSIVELY: u32 = 4;
pub const FS_RENAME_FILE: u32 = 5;
pub const FS_RENAME_DIRECTORY: u32 = 6;
pub const FS_GET_ENTRY_TYPE: u32 = 7;
pub const FS_OPEN_FILE: u32 = 8;
pub const FS_OPEN_DIRECTORY: u32 = 9;
pub const FS_COMMIT: u32 = 10;
pub const FS_GET_FREE_SPACE: u32 = 11;
pub const FS_GET_TOTAL_SPACE: u32 = 12;
pub const FS_CLEAN_DIRECTORY_RECURSIVELY: u32 = 13;
pub const FS_GET_FILE_TIME_STAMP_RAW: u32 = 14;
pub const FS_QUERY_ENTRY: u32 = 15;
pub const FS_GET_FILE_SYSTEM_ATTRIBUTE: u32 = 16;

// IFile
pub const FILE_READ: u32 = 0;
pub const FILE_WRITE: u32 = 1;
pub const FILE_FLUSH: u32 = 2;
pub const FILE_SET_SIZE: u32 = 3;
pub const FILE_GET_SIZE: u32 = 4;
pub const FILE_OPERATE_RANGE: u32 = 5;

// IDirectory
pub const DIR_READ: u32 = 0;
pub const DIR_GET_ENTRY_COUNT: u32 = 1;

// IStorage
pub const STORAGE_READ: u32 = 0;
pub const STORAGE_WRITE: u32 = 1;
pub const STORAGE_FLUSH: u32 = 2;
pub const STORAGE_SET_SIZE: u32 = 3;
pub const STORAGE_GET_SIZE: u32 = 4;
pub const STORAGE_OPERATE_RANGE: u32 = 5;

// ISaveDataInfoReader
pub const SAVE_DATA_INFO_READER_READ: u32 = 0;

// IEventNotifier
pub const EVENT_NOTIFIER_GET_EVENT_HANDLE: u32 = 0;

// IDeviceOperator
pub const DEVICE_OPERATOR_IS_SD_CARD_INSERTED: u32 = 0;
pub const DEVICE_OPERATOR_GET_SD_CARD_SPEED_MODE: u32 = 1;
pub const DEVICE_OPERATOR_GET_SD_CARD_CID: u32 = 2;
pub const DEVICE_OPERATOR_GET_SD_CARD_USER_AREA_SIZE: u32 = 3;
pub const DEVICE_OPERATOR_GET_SD_CARD_PROTECTED_AREA_SIZE: u32 = 4;
pub const DEVICE_OPERATOR_GET_AND_CLEAR_SD_CARD_ERROR_INFO: u32 = 5;
pub const DEVICE_OPERATOR_GET_MMC_CID: u32 = 100;
pub const DEVICE_OPERATOR_GET_MMC_SPEED_MODE: u32 = 101;
pub const DEVICE_OPERATOR_GET_MMC_PATROL_COUNT: u32 = 112;
pub const DEVICE_OPERATOR_GET_AND_CLEAR_MMC_ERROR_INFO: u32 = 113;
pub const DEVICE_OPERATOR_GET_MMC_EXTENDED_CSD: u32 = 114;
pub const DEVICE_OPERATOR_IS_GAME_CARD_INSERTED: u32 = 200;
pub const DEVICE_OPERATOR_GET_GAME_CARD_HANDLE: u32 = 202;
pub const DEVICE_OPERATOR_GET_GAME_CARD_UPDATE_PARTITION_INFO: u32 = 203;
pub const DEVICE_OPERATOR_GET_GAME_CARD_ATTRIBUTE: u32 = 205;
pub const DEVICE_OPERATOR_GET_GAME_CARD_DEVICE_CERTIFICATE: u32 = 206;
pub const DEVICE_OPERATOR_GET_GAME_CARD_ID_SET: u32 = 208;
pub const DEVICE_OPERATOR_GET_GAME_CARD_ERROR_REPORT_INFO: u32 = 217;
pub const DEVICE_OPERATOR_GET_GAME_CARD_DEVICE_ID: u32 = 218;
pub const DEVICE_OPERATOR_CHALLENGE_CARD_EXISTENCE: u32 = 219;
