[package]
name = "nx-service-async"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_service_async"
crate-type = ["rlib"]
test = false
doctest = false
bench = false

[dependencies]
nx-panic-handler = { version = "0.1.0", path = "../nx-panic-handler" }
nx-sf = { version = "0.1.0", path = "../nx-sf" }
nx-svc = { version = "0.1.0", path = "../nx-svc" }
static_assertions = "1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
