option(
    'use_nx_service_applet',
    type : 'feature', value : 'auto',
    description : 'Enable the nx-rt-core `service-applet` feature',
    yield : true
)

option(
    'use_nx_sys_net',
    type : 'feature', value : 'auto',
    description : 'Enable the socket driver initialization override (socketInitialize)',
    yield : true
)

option(
    'use_nx_net',
    type : 'feature', value : 'auto',
    description : 'Enable the resolver overrides that need the service-manager session',
    yield : true
)

option(
    'use_nx_sys_thread',
    type : 'feature', value : 'auto',
    description : 'Enable the nx-rt-core `sys-thread` feature',
    yield : true
)

option(
    'use_nx_sys_mem',
    type : 'feature', value : 'auto',
    description : 'Enable the nx-rt-core `sys-virtmem` feature',
    yield : true
)
