[package]
name = "nx-std-fs"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_std_fs"
crate-type = ["rlib"]
test = false
doctest = false
bench = false

[dependencies]
nx-alloc = { version = "0.1.0", path = "../nx-alloc", features = ["global-allocator"] }
nx-panic-handler = { version = "0.1.0", path = "../nx-panic-handler" }
nx-std-path = { version = "0.1.0", path = "../nx-std-path" }
nx-sys-fd = { version = "0.1.0", path = "../nx-sys-fd" }
thiserror = { version = "2.0.12", default-features = false }
