option(
    'use_nx_service_apm',
    type : 'feature', value : 'auto',
    description : 'Enable the nx-rt `service-apm` feature',
    yield : true
)

option(
    'use_nx_service_applet',
    type : 'feature', value : 'auto',
    description : 'Enable the nx-rt `service-applet` feature',
    yield : true
)

option(
    'use_nx_service_hid',
    type : 'feature', value : 'auto',
    description : 'Enable the nx-rt `service-hid` feature',
    yield : true
)

option(
    'use_nx_service_nv',
    type : 'feature', value : 'auto',
    description : 'Enable the nx-rt `service-nv` feature',
    yield : true
)

option(
    'use_nx_service_set',
    type : 'feature', value : 'auto',
    description : 'Enable the nx-rt `service-set` feature',
    yield : true
)

option(
    'use_nx_service_time',
    type : 'feature', value : 'auto',
    description : 'Enable the nx-rt `service-time` feature',
    yield : true
)

option(
    'use_nx_service_vi',
    type : 'feature', value : 'auto',
    description : 'Enable the nx-rt `service-vi` feature',
    yield : true
)
