[package]
name = "nx-sys-env"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_sys_env"
crate-type = ["rlib"]
test = false
doctest = false
bench = false

[dependencies]
nx-alloc = { version = "0.1.0", path = "../nx-alloc", features = ["global-allocator"] }
nx-panic-handler = { version = "0.1.0", path = "../nx-panic-handler" }
nx-sys-sync = { version = "0.1.0", path = "../nx-sys-sync" }
thiserror = { version = "2.0", default-features = false }
