[package]
name = "nx-service-nfc"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_service_nfc"
crate-type = ["rlib"]
test = false
doctest = false
bench = false

[dependencies]
bitflags = "2"
nx-panic-handler = { version = "0.1.0", path = "../nx-panic-handler" }
nx-service-mii = { version = "0.1.0", path = "../nx-service-mii" }
nx-service-sm = { version = "0.1.0", path = "../nx-service-sm" }
nx-sf = { version = "0.1.0", path = "../nx-sf" }
static_assertions = "1"
thiserror = { version = "2", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
