[package]
name = "nx-service-applet-err"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_service_applet_err"
crate-type = ["rlib"]
test = false
doctest = false
bench = false

[dependencies]
nx-panic-handler = { version = "0.1.0", path = "../nx-panic-handler" }
nx-service-applet = { version = "0.1.0", path = "../nx-service-applet" }
nx-sf = { version = "0.1.0", path = "../nx-sf" }
static_assertions = "1"
thiserror = { version = "2", default-features = false }
zerocopy = { workspace = true }
