[package]
name = "nx-netloader"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_netloader"
crate-type = ["rlib", "staticlib"]
test = false
doctest = false
bench = false

[features]
# Enable the __nx_netloader FFI
ffi = []

[dependencies]
nx-cpu = { version = "0.1.0", path = "../nx-cpu" }
nx-std = { version = "0.1.0", path = "../nx-std", default-features = false, features = ["fs", "extern-state"] }
nx-std-path = { version = "0.1.0", path = "../nx-std-path" }
nx-svc = { version = "0.1.0", path = "../nx-svc" }
nx-alloc = { version = "0.1.0", path = "../nx-alloc", features = ["global-allocator"] }
nx-panic-handler = { version = "0.1.0", path = "../nx-panic-handler" }
nx-sys-net = { version = "0.1.0", path = "../nx-sys-net", features = ["extern-state"] }
thiserror = { version = "2.0.12", default-features = false }
miniz_oxide = { version = "0.8", default-features = false, features = ["with-alloc"] }
